import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface EmailRequest {
  clientEmail: string;
  clientName: string;
  copyEmail: string;
  reportHtml: string;
  overallScore: number;
}

const handler = async (req: Request): Promise<Response> => {
  console.log('Email function called with method:', req.method);
  
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    console.log('Handling CORS preflight');
    return new Response(null, { 
      status: 200,
      headers: corsHeaders 
    });
  }

  try {
    const { clientEmail, clientName, copyEmail, reportHtml, overallScore }: EmailRequest = await req.json();

    console.log("Sending email to:", clientEmail, "with copy to:", copyEmail);

    const emailSubject = `Your ISO 9001 Assessment Report - ${overallScore}% Readiness`;
    
    console.log("Preparing to send email:", {
      to: clientEmail,
      cc: copyEmail,
      subject: emailSubject
    });

    const emailResponse = await resend.emails.send({
      from: "QSE Academy <noreply@qse-academy.com>",
      to: [clientEmail],
      cc: [copyEmail],
      subject: emailSubject,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Your ISO 9001 Assessment Report</title>
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background-color: #f4f4f4;">
          <div style="max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1);">
            <div style="text-align: center; margin-bottom: 30px;">
              <img src="https://wespmcyzcpyammqtjqqv.supabase.co/storage/v1/object/public/reports/qse-academy-logo.png" alt="QSE Academy Logo" style="width: 200px; height: auto; margin-bottom: 20px;">
              <h1 style="color: #2563eb; margin: 0;">ISO 9001 Assessment Report</h1>
              <p style="color: #666; font-size: 16px; margin: 10px 0 0 0;">QSE Academy</p>
            </div>
            
            <div style="margin-bottom: 30px;">
              <h2 style="color: #333;">Dear ${clientName},</h2>
              <p style="color: #666; font-size: 16px;">
                Thank you for completing your ISO 9001 readiness assessment. Your detailed report is included below.
              </p>
              <p style="color: #666; font-size: 16px;">
                <strong>Overall Readiness Score: ${overallScore}%</strong>
              </p>
            </div>

            <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
              <h3 style="color: #2563eb; margin-top: 0;">What's Next?</h3>
              <ul style="color: #666; padding-left: 20px;">
                <li>Review your detailed assessment results below</li>
                <li>Focus on areas that need improvement</li>
                <li>Consider professional ISO 9001 consultation</li>
                <li>Take steps to implement quality management systems</li>
              </ul>
            </div>

            <div style="text-align: center; margin-bottom: 30px;">
              <p style="color: #666; font-size: 14px;">
                Need help implementing ISO 9001? Our experts are here to guide you through the certification process.
              </p>
              <a href="mailto:support@qse-academy.com" style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">
                Contact Our Experts
              </a>
            </div>

            <hr style="border: none; height: 1px; background-color: #e5e7eb; margin: 30px 0;">

            ${reportHtml}

            <hr style="border: none; height: 1px; background-color: #e5e7eb; margin: 30px 0;">

            <div style="text-align: center; color: #666; font-size: 12px;">
              <p>This report was generated by QSE Academy ISO 9001 Assessment Tool.</p>
              <p>© ${new Date().getFullYear()} QSE Academy. All rights reserved.</p>
            </div>
          </div>
        </body>
        </html>
      `,
    });

    console.log("Email sent successfully:", emailResponse);

    return new Response(JSON.stringify({ success: true, messageId: emailResponse.data?.id }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error sending email:", error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message || "Failed to send email" 
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);